#!/bin/bash

get_os(){
  if [ -f "/etc/apt/sources.list" ]; then
    if [ -f "/etc/lsb-release" ]; then
      os_version=$(cat /etc/lsb-release | grep  "DISTRIB_RELEASE" | cut -d= -f2)
      echo "UBUNTU $os_version"
    elif [ -f "/etc/debian_version" ]; then
      os_version=$(cat /etc/debian_version | cut -d. -f1)
      echo "DEBIAN $os_version"
    fi
  elif [ -d "/etc/yum.repos.d" ]; then
    os_version="$(cat /etc/system-release | grep -o '[0-9]\.[0-9]')"
    echo "RHEL $os_version"
  else
    echo "UNKOWN"
  fi
}
